
export const actionTypes = {
  // app
  TOGGLE_MENU: 'TOGGLE_MENU',

  // product
  FIND_MANY_PRODUCTS: 'FIND_MANY_PRODUCTS',
  FIND_MANY_PRODUCTS_SUCCESS: 'FIND_MANY_PRODUCTS_SUCCESS',
  FIND_MANY_PRODUCTS_FAILURE: 'FIND_MANY_PRODUCTS_FAILURE',

  PASSWORD_LOGIN: 'PASSWORD_LOGIN',
  PASSWORD_LOGIN_SUCCESS: 'PASSWORD_LOGIN_SUCCESS',
  PASSWORD_LOGIN_FAILURE: 'PASSWORD_LOGIN_FAILURE',

  FIND_ME_SUCCESS: 'FIND_ME_SUCCESS',
}
