
export const actionTypes = {
  // APP
  TOGGLE_MENU: 'TOGGLE_MENU',
  CHANGE_NAVIGATION_MODE: 'CHANGE_NAVIGATION_MODE',

  // USER
  USERS_FAILURE: 'USERS_FAILURE',

  FIND_MANY_USERS_REQUEST: 'FIND_MANY_USERS_REQUEST',
  FIND_MANY_USERS_SUCCESS: 'FIND_MANY_USERS_SUCCESS',
  FIND_MANY_USERS_FAILURE: 'FIND_MANY_USERS_FAILURE',

  DELETE_MANY_USERS_REQUEST: 'DELETE_MANY_USERS_REQUEST',
  DELETE_MANY_USERS_SUCCESS: 'DELETE_MANY_USERS_SUCCESS',

  DELETE_ONE_USER_REQUEST: 'DELETE_ONE_USER_REQUEST',
  DELETE_ONE_USER_SUCCESS: 'DELETE_ONE_USER_SUCCESS',
  DELETE_ONE_USER_FAILURE: 'DELETE_ONE_USER_FAILURE',


  FIND_ONE_USER_REQUEST: 'FIND_ONE_USER_REQUEST',
  FIND_ONE_USER_SUCCESS: 'FIND_ONE_USER_SUCCESS',

  CREATE_ONE_USER_SUCCESS: 'CREATE_ONE_USER_SUCCESS',
  CREATE_ONE_USER_FAILURE: 'CREATE_ONE_USER_FAILURE',
  CREATE_ONE_USER_REQUEST: 'CREATE_ONE_USER_REQUEST',

  UPDATE_ONE_USER_REQUEST: 'UPDATE_ONE_USER_REQUEST',
  UPDATE_ONE_USER_FAILURE: 'UPDATE_ONE_USER_FAILURE',
  UPDATE_ONE_USER_SUCCESS: 'UPDATE_ONE_USER_SUCCESS',

  //AUTH
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_FAILURE: 'AUTH_FAILURE',

  PASSWORD_LOGIN_SUCCESS: 'PASSWORD_LOGIN_SUCCESS',
  FIND_ME_SUCCESS: 'FIND_ME_SUCCESS',

  // ROLE
  FIND_MANY_ROLES_SUCCESS: 'FIND_MANY_ROLES_SUCCESS',
  FIND_ONE_ROLE_SUCCESS: 'FIND_ONE_ROLE_SUCCESS',


  // PERSONNEL
  FIND_MANY_PERSONNEL_REQUEST: 'FIND_MANY_PERSONNEL_REQUEST',
  FIND_MANY_PERSONNEL_SUCCESS: 'FIND_MANY_PERSONNEL_SUCCESS',
  FIND_MANY_PERSONNEL_FAILURE: 'FIND_MANY_PERSONNEL_FAILURE',

}
